//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTG {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\NUnit 2.5.10\\bin\\net-2.0\\framework")]
        public string UnitBinariesDirectory {
            get {
                return ((string)(this["UnitBinariesDirectory"]));
            }
            set {
                this["UnitBinariesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\NUnit 2.5.10\\bin\\net-2.0")]
        public string UnitConsoleDirectory {
            get {
                return ((string)(this["UnitConsoleDirectory"]));
            }
            set {
                this["UnitConsoleDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\NUnit 2.5.10\\bin\\net-2.0")]
        public string UnitCommandsDirectory {
            get {
                return ((string)(this["UnitCommandsDirectory"]));
            }
            set {
                this["UnitCommandsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Tab {
            get {
                return ((int)(this["Tab"]));
            }
            set {
                this["Tab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CoverageConsoleDirectory {
            get {
                return ((string)(this["CoverageConsoleDirectory"]));
            }
            set {
                this["CoverageConsoleDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CoverageCommandsDirectory {
            get {
                return ((string)(this["CoverageCommandsDirectory"]));
            }
            set {
                this["CoverageCommandsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CoverageBinariesDirectory {
            get {
                return ((string)(this["CoverageBinariesDirectory"]));
            }
            set {
                this["CoverageBinariesDirectory"] = value;
            }
        }
    }
}
